name: resource_manager_model
version: '1.0.0'
profile: resource_manager
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  resource_manager_model:
    models:
      staging:
        +materialized: view  
